### ISSUE TITLE
Need to fix on search and order functionality

### ISSUE THREAD

**Issue by q7zh** [q7zh/CS188-Dicom#2]
### On search_start page:
1. Make the both search bars longer so that it can fit the width of the screen (look into normal mobile version search bar)
2. Make the search bars round corner: 25px
3. Remove go button and use enter to search the string instead
4. Remove go to profile button on the top left
5. Rename the title “Search for a restaurant” into “Search”
6. Make the table share and time button under the search bar and align left 
### On search_Korean page:

1. Same as search_start page
2. Remove 1. 2. 3… in the restaurant list
3. Make the restaurant list a slidable area (optional)

### On BCD_restaurantMenu page:

1. Change the go to profile button on the top left into a back button
2. Rename the title “Restaurant Menu” into “Menu”
3. Somehow on my computer the half yellow star is misplaced, probably remove unnecessary code can fix it?
4. Remove service button

### On item pages:

1. Change the go to profile button on the top left into a back button
2. Move the prices under the description
3. Put add to cart button at the bottom of the page
4. Add notes section
5. Firebase support:
- When click on add to cart button, write these data to the database collection 'Items':
- [x] Title
- [x] Price
- [x] Quantity
- [x]  Notes
- Read the data from the database (if there is any) and show it in the item page so that after a user add an item to the cart and click into the just added item page again, he can see the info he put in just now (like the quantity and notes)
6. Make the menu or the whole page a slidable area (optional)
7. Use the button similar to that in service part to add item's quantity instead of choosing the quantity from a list
8.  Move and align the select quantity button to the right
9. Remove "please select quantity:"

**Comment by ktolby** [comment]
All completed, with the following exceptions:

- [Multiple] None of the pages were made slideable
- [RestaurantMenu] Don't know how to replicate the misplaced yellow star on restaurantMenu, so issue left untouched
- [Item Pages] Prices were _not_ moved to under item description
- [Item Pages] Quantity was _not_ moved to right hand side
